language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - 2.4.0

gemfile:
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile

addons:
  code_climate:
    repo_token: abb288da5fac3efc45be30ffb37085314b9189ddccedf2cc68282777477e21c5

after_success:
  - bundle exec codeclimate-test-reporter

matrix:
  exclude:
    # rails 5 requires 2.2+
    - rvm: 2.1.8
      gemfile: gemfiles/5.0.gemfile

    # Arel support for ruby 2.4 starts in 4.2
    - rvm: 2.4.0
      gemfile: gemfiles/4.0.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/4.1.gemfile