language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0

addons:
  code_climate:
    repo_token: abb288da5fac3efc45be30ffb37085314b9189ddccedf2cc68282777477e21c5

after_success:
  - bundle exec codeclimate-test-reporter
