language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5.0
  - 2.6.0

gemfile:
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile

addons:
  code_climate:
    repo_token: abb288da5fac3efc45be30ffb37085314b9189ddccedf2cc68282777477e21c5

after_success:
  - bundle exec codeclimate-test-reporter
